### ISSUE TITLE
extra install step

### ISSUE THREAD

**Issue by LukeLabrie** [openmsr/CAD_to_openMC#13]
To get moab to work after (from readme)

```
mkdir build; cd build; cmake .. -DENABLE_PYMOAB=1 -DCMAKE_INSTALL_PREFIX=<path/to/venv/>; make; make install
```
I had to also run 

```
cd pymoab; python setup.py install
```

I don't quite remember why this is necessary but it's also part of our install scripts. Perhaps it should be included in the readme instructions?

**Comment by ebknudsen** [comment]
I think you're right. I will add that.

**Comment by ebknudsen** [comment]
done _ closing
