### ISSUE TITLE
InverseCSG

### ISSUE THREAD

**Issue by kozmad** [openmsr/CAD_to_OpenMC#38]
Dear developers,

I've just found an interesting paper on the internet. I don't know if you are familiar with it, but I thought It might be useful to you:
[InverseCSG: Automatic Conversion of 3D Models to CSG](http://inversecsg.csail.mit.edu/)
Paper and code can be found there as well.

Cheers,
Daniel

**Comment by ebknudsen** [comment]
Thanks for bringing this to our attention - we shall take a look :-)

**Comment by ebknudsen** [comment]
This is very interesting - but has little implications for this project. Closing for now
