### ISSUE TITLE
gmesh backend fails to give stl attribute to Entity object following merge

### ISSUE THREAD

**Issue by LukeLabrie** [openmsr/CAD_to_OpenMC#52]
Using the following script:

```python
import CAD_to_OpenMC.assembly as ab
a=ab.Assembly()
a.stp_files=["./fuel_pins.step"]
a.import_stp_files()
a.merge_all()
a.solids_to_h5m(backend="gmsh")
```

produces the following error 

```
Traceback (most recent call last):
  File "/home/luke/git/aur/openmc-git/step_to_h5m.py", line 6, in <module>
    a.solids_to_h5m()
  File "/usr/lib/python3.10/site-packages/CAD_to_OpenMC/assembly.py", line 374, in solids_to_h5m
    stl_list=self.heal_stls(stl_list)
  File "/usr/lib/python3.10/site-packages/CAD_to_OpenMC/assembly.py", line 622, in heal_stls
    stl=e.stl
AttributeError: 'Entity' object has no attribute 'stl'

```
for this [step file](https://github.com/openmsr/CAD_to_OpenMC/files/11031195/fuel_pins.step.tar.gz).

Since gmesh is currently the default backend, this also occurs when I don't specify a backend. 

Let me know if I can provide more detail.

**Comment by LukeLabrie** [comment]
I've discovered that if I comment out the merge operation, the error goes away, but the mesh is of course not merged in that case. So this might have something to do with the merge step

**Comment by ebknudsen** [comment]
I think this is caused by the stl attribute not being set in the correct scope. I'll look into it.

**Comment by ebknudsen** [comment]
This was caused by the meshing backend setting the stl attribute on the Entity objects. This failed in some instances for whatever reason. If the constructed stl-filenames are instead returned to the host class and explicitly added there it works.
