### ISSUE TITLE
Simplify Gmsh brep import

### ISSUE THREAD

**Issue by akoen** [openmsr/CAD_to_OpenMC#59]
OCC objects can be directly imported into Gmsh using a native pointer instead of exporting and importing a brep file.

https://github.com/openmsr/CAD_to_OpenMC/blob/18a138f0bf23d02ce95d48f79961f923031acd33/src/CAD_to_OpenMC/assemblymesher_gmsh.py#L92C21-L92C21

See Cad-to-DAGMC:
https://github.com/fusion-energy/cad_to_dagmc/blob/bf0243cb4f8de46d0958760a12b83610dedffdc5/src/cad_to_dagmc/brep_to_h5m.py#L32C6-L32C6

**Comment by ebknudsen** [comment]
Thanks for the comment - this is scheduled to happen in the overnext release.

**Comment by ebknudsen** [comment]
This fix will have to be postponed as originally intended as I can't seem to get it to work reliably right now. Reverting 37aa015de657f014e68e2481a447917f1f51463b for now.

**Comment by ebknudsen** [comment]
closing as a wont fix for now. This should really be taken care of more generally as a solution to #105
